### ISSUE TITLE
Sfx checklist

### ISSUE THREAD

**Issue by warriormaster12** [warriormaster12/SubmarineSurvival#13]
General checkbox list that can be edited down the line

Submarine:
- [ ] Engine start/stop sound?
- [ ] Engine idle sound
- [ ] Engine moving sound
- [ ] Impact low
- [ ] Impact medium
- [ ] Impact high
- [ ] sparks
